# Generated by Django 5.0.4 on 2024-04-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='image',
        ),
        migrations.AddField(
            model_name='music',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
