# Generated by Django 5.0.4 on 2024-04-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musics', '0002_remove_music_image_music_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
