# Generated by Django 5.0.4 on 2024-04-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musics', '0003_alter_music_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='size',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='music',
            name='release_date',
        ),
    ]
